### ISSUE TITLE
How is SLOC calculated?

### ISSUE THREAD

**Issue by MorevM** [cqfn/kaicode.github.io#24]
Hello,

I would like to get clarification on how the SLOC score is calculated. 
It would be a little awkward to get disqualified because of a formal failure to meet the criteria.

[In previous years](https://www.yegor256.com/2019/11/03/award-2020.html) there was a clarification "`cloc` without any arguments" (without taking external dependencies into account, I guess), this year I don't see the criteria, so I have a question.

If I have a large readme - does it count?
Configuration files (linters, dependency list, compiler and test framework settings, build and publish scripts)?
Github interaction and consumer information (`license.md`, `changelog.md`, issue and pull request templates, `dependabot` settings?).
Playground/docs/demo as a website inside the repository?
Comments on TS types in JSDoc format? Technically, it's a comment, but it's what adds value to the end user.
And so on.

One of my projects that I would like to submit fulfills the criteria if I run `cloc . --exclude-dir=node_modules`, but if I exclude the "technical" files that are required to make the work comfortable and explain to consumers what the product does (`cloc ./src`), then the criterion is no longer met.

I also think it would be good to post the answer to this request on the main contest site. 

Thanks. :)

**Comment by maxonfjvipon** [comment]
@MorevM thanks for your answer, that's really important. How we count: 
1. `cloc` without arguments
2. counting only first 3 lines
3. without comments

We'll post the info on the website soon!

**Comment by yegor256** [comment]
@MorevM the answer has also been published on our website
